//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayMore_V5._0.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Booking
    {
        public int BookId { get; set; }
        public string BookedBy_Userid { get; set; }

        [Required(ErrorMessage = "Please Enter First Name")]
        [Display(Name = "First name")]
        public string BookFName { get; set; }

        [Required(ErrorMessage = "Please Enter Last Name")]
        [Display(Name = "Last name")]
        public string BookLName { get; set; }

        [Required(ErrorMessage = "Please Enter Age")]
        [Display(Name = "Age")]
        public string BookAge { get; set; }
        public int WorkshopWorkshopId { get; set; }
    
        public virtual Workshop Workshop { get; set; }
    }
}
