//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayMore_V5._0.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Coach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coach()
        {
            this.Workshops = new HashSet<Workshop>();
        }
    
        public int CoachId { get; set; }

        [Required(ErrorMessage = "Please Enter First Name of Coach")]
        [Display(Name = "First name")]
        public string CoachFName { get; set; }

        [Required(ErrorMessage = "Please Enter Last Name of Coach")]
        [Display(Name = "Last name")]
        public string CoachLName { get; set; }

        [Required(ErrorMessage = "Please Coach Email")]
        [Display(Name = "Email")]
        public string CoachEmail { get; set; }

        [Display(Name ="Game Name")]
        public int GameGameId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Workshop> Workshops { get; set; }
        public virtual Game Game { get; set; }
    }
}
